version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: identity_app
    ports:
      - "5000:8080"
  polkadot_node:
    image: parity/polkadot:v0.8.24
    container_name: polkadot_node
    command: --name "polkadot archive node" --rpc-external --ws-external --pruning archive
    ports: 
      - "9944:9944"
      - "9933:9933"
    volumes:
      - type: bind
        source: /home/ubuntu/node_data/polkadot/
        target: /polkadot
  # kusama_node:
  #   image: 
  #   container_name: kusama_node
  #   command: 
  polkadot_indexer:
    build:
      context: .
      dockerfile: docker/Dockerfile.indexer
    container_name: polkadot_indexer
    environment: 
      - CHAIN_DATA_DB="/home/$USER/.local/share/polkadot"
      - DATABASE_URL="postgres://sourcify:test@postgres/identity"
  # kusama_indexer:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.client
  #   container_name: kusama_indexer
  polkadot_postgres:
    image: postgres:13
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    # env_file: .env
  # kusama_postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
  #   env_file: .env
  nginx:
    image: steveltn/https-portal
    container_name: https-portal
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'identity.shardlabs.io -> http://identity_app:8080'
      STAGE: 'staging'
      FORCE_RENEW: 'false'
    depends_on:
      - client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  
