version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: identity_app
    ports:
      - "5000:8080"
  polkadot_node:
    image: parity/polkadot:v0.8.24
    container_name: polkadot_node
    command: --name "polkadot archive node" --rpc-external --ws-external --pruning archive
  # kusama_node:
  #   image: 
  #   container_name: kusama_node
  #   command: 
  polkadot_indexer:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: polkadot_indexer
  # kusama_indexer:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.client
  #   container_name: kusama_indexer
  polkadot_postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: .env
  # kusama_postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
  #   env_file: .env
  
