version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: identity_app
  polkadot_node:
    image: parity/polkadot:v0.9.8
    container_name: polkadot_node
    command: --name "polkadot archive node" --rpc-external --rpc-cors all --ws-external --pruning archive
    volumes:
      - type: bind
        source: /home/ubuntu/node_data/polkadot/
        target: /polkadot/.local/share/polkadot/chains/polkadot
      
  kusama_node:
    image: parity/polkadot:v0.9.8
    container_name: kusama_node
    command: --name "kusama archive node" --chain kusama --rpc-external --rpc-cors all --ws-external --pruning archive
    volumes:
      - type: bind
        source: /home/ubuntu/node_data/ksmcc3/
        target: /polkadot/.local/share/polkadot/chains/ksmcc3
    
  # polkadot_indexer:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.indexer
  #   container_name: polkadot_indexer
  #   volumes:
  #     - type: bind
  #       source: /home/ubuntu/node_data/polkadot/
  #       target: /root/.local/share/polkadot/
  #   environment: 
  #     - CHAIN_DATA_DB="/root/.local/share/polkadot/db"
  #     - DATABASE_URL="postgres://postgres:polkadot@polkadot_postgres:5432/polkadot-archive"
  #   depends_on:
  #     - polkadot_postgres
  # kusama_indexer:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.client
  #   container_name: kusama_indexer
  # polkadot_postgres:
  #   image: postgres:13
  #   container_name: polkadot_postgres
  #   volumes:
  #     - type: bind
  #       source: /home/ubuntu/postgres_data/polkadot/
  #       target: /var/lib/postgresql/data
  #   env_file: .env
  #   ports:
  #     - "5432:5432"
  # kusama_postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
  #   env_file: .env
  nginx:
    image: steveltn/https-portal
    container_name: https-portal
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'identityhub.xyz -> http://identity_app:5000, rpc.identityhub.xyz -> http://polkadot_node:9944, kusama-rpc.identityhub.xyz -> http://kusama_node:9944'
      STAGE: 'production'
      FORCE_RENEW: 'false'
    depends_on:
      - client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  
