[chain]

data_path = "/root/.local/share/polkadot/db"

[database]

url = "postgres://postgres:miroslav@polkadot_postgres:5432/polkadot-archive"

[wasm_tracing]

targets = '''wasm_tracing,pallet,frame,state'''

#folder = "root/.local/share/polkadot/wasm-tracing"